@echo off
echo Killing Dart processes...
taskkill /F /IM dart.exe /T
echo Killing Flutter processes...
taskkill /F /IM flutter.exe /T
echo Killing Chrome processes (careful, this closes all Chrome windows)...
taskkill /F /IM chrome.exe /T
echo Cleanup complete.
