"""add_image_urls_to_vehicle

Revision ID: ad6241fb6acb
Revises: bb7c7ba64d73
Create Date: 2026-02-15 16:02:36.017115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad6241fb6acb'
down_revision: Union[str, None] = 'bb7c7ba64d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('image_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'image_urls')
    # ### end Alembic commands ###
