"""Add featured vehicle fields

Revision ID: bb7c7ba64d73
Revises: 360b87bd03ca
Create Date: 2026-02-12 10:16:24.763695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7c7ba64d73'
down_revision: Union[str, None] = '360b87bd03ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'description')
    op.drop_column('vehicles', 'lng')
    op.drop_column('vehicles', 'lat')
    op.drop_column('vehicles', 'rating')
    op.drop_column('vehicles', 'image_url')
    # ### end Alembic commands ###
